### PR TITLE
Publication ready cargo.toml

### PR DESCRIPTION
**Pull request by jgur-psyops**
Prepare crate for publication on crates.io

CPI instructions working as intended, all tests pass.

### CODE REVIEW

**Comment by iurage** [comment]
Added @KaustubhShamshery as a reviewer

**Review by iurage — COMMENTED** [review]
- Rename PsyDO as PsyDAO
- I saw in withdraw_tokens that `psy_program` is ahead of `token_program`. Wouldn't the vec of accounts need to follow the same order as defined in the IDL?

**Comment by iurage** [comment]
We should publish this under the org if possible + add a release tag to this when its done. Could also add a short doc here on how to integrate, for a yield aggregator:
1. Initialize token account owned by user program for deposit note. `init_deposit_account` should not be used.
2. For deposit, CPI to accrual_interest and deposit_tokens in same IX
3. For withdraw, CPI to accrual_interest and withdraw_tokens in same IX

Also would be good if we add util functions within this crate:
- get total_depositt
- utilization
- interest rate model
- deposit_limit

**Comment by KaustubhShamshery** [comment]
Can you check the params of `deposit_tokens` cpi with the original psylend. Seems to be an inconsistency.

**Comment by jgur-psyops** [comment]
> * Rename PsyDO as PsyDAO
> * I saw in withdraw_tokens that `psy_program` is ahead of `token_program`. Wouldn't the vec of accounts need to follow the same order as defined in the IDL?

Fixed the issue with withdraw_tokens and added a test.

Not sure where the word "PsyDo" appears.

**Comment by jgur-psyops** [comment]
> We should publish this under the org if possible + add a release tag to this when its done. Could also add a short doc here on how to integrate, for a yield aggregator:
> 
> 1. Initialize token account owned by user program for deposit note. `init_deposit_account` should not be used.
> 2. For deposit, CPI to accrual_interest and deposit_tokens in same IX
> 3. For withdraw, CPI to accrual_interest and withdraw_tokens in same IX

Added an example "combination CPI" ix and a test that demonstrates this usage.

> Also would be good if we add util functions within this crate:
> 
> * get total_depositt
> * utilization
> * interest rate model
> * deposit_limit

Imo, let's put this off until we have specific interest in these features from a third-party using the crate: we've spent a lot of dev time in the past on integrations before with little/no return. Added issue.

**Comment by jgur-psyops** [comment]
> Can you check the params of `deposit_tokens` cpi with the original psylend. Seems to be an inconsistency.

Fixed

**Review by iurage — COMMENTED** [review]
LGTM, nothing specific from my end

**Pull request merged**
